const configs = {
  API_URL: process.env.API_URL,
  FACEBOOK_URL: process.env.FACEBOOK_URL,
  FACEBOOK_REDIRECT_URI: process.env.FACEBOOK_REDIRECT_URI,
  FACDBOOK_CLIENT_ID: process.env.FACDBOOK_CLIENT_ID,
  GOOGLE_URL: process.env.GOOGLE_URL,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  LINKEDIN_URL: process.env.LINKEDIN_URL,
  LINKEDIN_REDIRECT_URI: process.env.LINKEDIN_REDIRECT_URI,
  LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
  GITHUB_URL: process.env.GITHUB_URL,
  GITHUB_REDIRECT_URI: process.env.GITHUB_REDIRECT_URI,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  BITBUCKET_URL: process.env.BITBUCKET_URL,
  BITBUCKET_REDIRECT_URI: process.env.BITBUCKET_REDIRECT_URI,
  BITBUCKET_CLIENT_ID: process.env.BITBUCKET_CLIENT_ID
}

export default configs
